kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: myclaim
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
                storage: 8GI
(In the Pod)
....
spec:
    containers:
    - name: ctr
      volumeMounts:
      - mountPath: /test
        name: test-volume
....
    volumes:
        - name: test-volume
          persistentVolumeClaim:
                claimName: myclaim