apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2024-11-08T13:59:17Z"
  name: my-sa--dry-run
  namespace: gatape-tools-rec
  resourceVersion: "1310008249"
  uid: f1cb431a-f9e0-4b50-a18c-62d4ae68428d